### ISSUE TITLE
Node Failure detection mechanism

### ISSUE THREAD

**Issue by digambar15** [metal3-io/metal3-docs#129]
**Problem Statement -** 

Airship community has come up with one requirement on how user will get to know what is the cause of failure on the host.
So it's the use case related to failure detection mechanism where user can get to know what has failed so that User can go and fix the perticular issue on the node.
At broader side, there are many reasons host will fail either in introspection or in day n scenarios. Following are the scenarios - 
Disk Errors - Some disks went into error/failed state, another point is raid creation is failed.
PXE Errors - It's because PXE NIC is not properly configured
Management and power Errors - Now able to power on the node or Node goes into recovery mode but it's not accessible.
Boot/Bios Errors - Boot is failed due to device settings are incorrect.

Currently from Ironic side, none of the above failures put into introspection data. I have done investigation but I never found these level of specifics which will help user identify reason behind the failure.

I thought through above scenarios, we can bring some classification for errors detection where we can classify hosts based on specific failures.
For that, we need to write entire failure detection mechanism in HCC. I will put my investigation and solution approach in google doc for more details.

**Comment by dhellmann** [comment]
We looked at this for OpenShift, and came to the conclusion that the turn-around time for reporting hardware issues for running hosts through the baremetal operator would be slower than if we added features to tools like node_exporter. I'm not sure if all of the classes of issues listed above could be detected by data node_exporter collects today, so we may either need to add to node_exporter or at the very least ensure it is configured to report metal-specific data like SMART status for disks.

The BMO should report issues with ironic operations, since if inspection or provisioning fail then the host won't ever become a node and won't be able to run node_exporter and the BMO knows about the problem. I think we do put the host into an error state for those cases, although https://github.com/metal3-io/baremetal-operator/pull/610 will mean the host doesn't stay in that state and we continuously retry the operation, so that might affect how the error is detected by a monitoring tool. We should ensure that the right prometheus metric for each failure is still updated as part of that work.

**Comment by dhellmann** [comment]
https://github.com/metal3-io/ironic-prometheus-exporter may also be a useful way to report some of the stats that Ironic can collect out of band via the BMC.

**Comment by digambar15** [comment]
I have gone through the node-exporter previously, most of the error node-exporter doesn't reproduce. I will certainly look into Ironic-prometheus-exporter in detail. Most probably we will have to implement this feature in one of these project. I will investigate more in both of these project and will discuss with you later for further implementation.
