### ISSUE TITLE
Define release guidelines for baremetal-operator and start publishing releases

### ISSUE THREAD

**Issue by Arvinderpal** [metal3-io/metal3-docs#71]
We should adopt a releasing approach similar to that of CAPI and follow the well-known semantic versioning guidelines (see references below).

Besides this being a good practice, integration with the redesigned clusterctl will require that projects follow the above mentioned releasing strategy. A similar issue was created for capbm: https://github.com/metal3-io/cluster-api-provider-baremetal/issues/224

PR Tracking:
- [ ] Makefile updates for docker build and push, and release manifests generation: https://github.com/metal3-io/baremetal-operator/pull/405
- [ ] #272

**Comment by russellb** [comment]
reopened, since this is still relevant

**Comment by fmuyassarov** [comment]
Reopening, since this has not been solved yet and still relevant

**Comment by fmuyassarov** [comment]
Yesterday during the community meeting we discussed the process of starting Baremetal Operator project releases. We are going to follow the widespread semantic versioning scheme and since we have not yet announced BMO as stable we would like to have more frequent and smaller releases for now and when we reach the stability we would like to stick to the same release cycle as Kubernetes (3 times a year). But we will discuss it again when the time comes for that.

To start with, our MAJOR version will be 0, until we feel that the codebase is stable enough for the production. As such, we could start with MINOR version 0.1.0 and continue incrementing from there.

Main branch will be for development while release-MINOR.PATCH branch is for stable, tested and backwards compatible code. Whenever there is a new major or minor release, a new branch will be created with release-MINOR.PATCH name.

**Comment by s3rj1k** [comment]
@fmuyassarov major version 0 can be an issue for go.mod

Are we sure that that kind of release versioning will be compatible for go.mod usage?

**Comment by fmuyassarov** [comment]
> 

What is the issue? We have been using it in CAPM3 until now.

**Comment by s3rj1k** [comment]
> 
> What is the issue? We have been using it in CAPM3 until now.

https://go.dev/doc/modules/version-numbers

Hmm, you are correct as per the link above.

I assume possible issue can be with v0 to v1 (creating a branch or subfolder)

**Comment by fmuyassarov** [comment]
> > What is the issue? We have been using it in CAPM3 until now.
> 
> https://go.dev/doc/modules/version-numbers
> 
> Hmm, you are correct as per the link above.
> 
> I assume possible issue can be with v0 to v1 (creating a branch or subfolder)

I don't see an issue in branching as well to be honest. But after your point, I realized that branch naming should not be release-MINOR.PATCH but instead release-MAJOR.MINOR because each MINOR can have 0,1,3..9 PATCH releases, and we don't want to create a branch for every single patch release. I will make correction on my email and thanks for pointing out.

**Comment by s3rj1k** [comment]
@fmuyassarov I was pointing out that go expects that new Major release shoulb be in separate branch or subfolder and named as Major version value.

So transition for v0 to v1, according to golang spec, we would need to put newer code in new branch named `v1` or into subfolder `v1`.

Not sure that this is actually needed for `v0` to `v1`, pretty much sure that this is needed for `v1` to `v2` transition.

**Comment by Rozzii** [comment]
I would close this I think this issue has been resolved but please give your opinion.

**Comment by furkatgofurov7** [comment]
> I would close this I think this issue has been resolved but please give your opinion.

+1

**Comment by Rozzii** [comment]
We have started releasing BMO and we have a release guideline in review https://github.com/metal3-io/baremetal-operator/pull/1170.
/close
